name: sample
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  route_pattern: 
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  build_runner: ^1.0.0
  route_pattern_generator:

dependency_overrides:
  route_pattern:
    path: ../route_pattern
  route_pattern_generator:
    path: ../route_pattern_generator 