name: route_pattern_generator
version: 0.7.2
description: A Dart static code generator that produces matchers and builders from route uri patterns.
homepage: https://github.com/aloisdeniel/route_pattern_generator

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  build_runner: ^1.12.2
  build: ^2.0.1
  recase: ^2.0.1
  code_builder: ^3.7.0 
  dart_style: ^1.3.14
  path: ^1.8.0 
  source_gen: ^0.9.10+4
  route_pattern: ^0.7.0

dev_dependencies:
  test: ^1.3.3