name: route_pattern_generator
version: 0.5.6
author: Aloïs Deniel <alois.deniel@outlook.com>
description: A Dart static code generator that produces matchers and builders from route uri patterns.
homepage: https://github.com/aloisdeniel/route_pattern_generator

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  recase: ^2.0.1
  analyzer: '>=0.32.2 <0.35.0'
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.4.0'
  code_builder: ^3.1.3
  dart_style: ^1.2.2
  path: ^1.3.2 
  source_gen: ^0.9.0 
  route_pattern: ^0.5.6

dev_dependencies:
  build_runner: ^1.0.0
  test: ^1.3.3

dependency_overrides:
  route_pattern:
    path: ../route_pattern