name: route_pattern_generator
version: 0.7.0
description: A Dart static code generator that produces matchers and builders from route uri patterns.
homepage: https://github.com/aloisdeniel/route_pattern_generator

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: '>=0.39.0 <0.40.0'
  build: ^1.2.0
  recase: ^2.0.1
  code_builder: ^3.1.3
  dart_style: ^1.2.2
  path: ^1.3.2 
  source_gen: ^0.9.4
  route_pattern: ^0.7.0

dev_dependencies:
  build_runner: ^1.0.0
  test: ^1.3.3