name: route_pattern
version: 0.5.6
author: Aloïs Deniel <alois.deniel@outlook.com>
description: A Dart static code generator that produces matchers and builders from route uri patterns.
homepage: https://github.com/aloisdeniel/route_pattern_generator

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.3