name: route_pattern
version: 0.7.0
description: A Dart static code generator that produces matchers and builders from route uri patterns.
homepage: https://github.com/aloisdeniel/route_pattern_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8